### ISSUE TITLE
Get this directly included in KiCAD?

### ISSUE THREAD

**Issue by Harvie** [micsche/kicad-laser-min#1]
Hello,
have you considered adding this as integral feature to the kicad and geting it merged? I think this might be neat addition to the "export" menu in pcbnew.

**Comment by micsche** [comment]
Definitely doable. Will send an email to kicad team.

**Comment by micsche** [comment]
No response from kicad team.

**Comment by Harvie** [comment]
I've tried to ask on their gitlab: https://gitlab.com/kicad/code/kicad/-/issues/7138

**Comment by Harvie** [comment]
They just proposed this to be implemented as KiCAD plugin. This makes sense to me.

**Comment by micsche** [comment]
That's good. What next?

**Comment by Harvie** [comment]
We have to figure out... But ultimately it should be easy to create simple wrapper plugin to execute unmodified kicad-laser-min from GUI.

**Comment by micsche** [comment]
kicad gui?

**Comment by Harvie** [comment]
> kicad gui?

yes. that is the point. create kicad plugin to launch kicad-laser-min directly from kicad gui.
