### ISSUE TITLE
Board outline

### ISSUE THREAD

**Issue by Harvie** [micsche/kicad-laser-min#2]
Would it be possible to add support for boards that are not square, but have custom shape instead... Eg. circle, oval, etc...
Basicaly just remove all isolation cuts that go outside of the board outline and add the outline to the g-code.
You can probably use some special color (or alpha channel?) to denote the pixels outside of the board during the bitmap stage and then modify the voronoi to not fill these pixels.

**Comment by micsche** [comment]
Can you show me in pictures?

**Comment by Harvie** [comment]
Input is not square:

![image](https://user-images.githubusercontent.com/276504/89265466-ce89c400-d634-11ea-8a94-0b3cc5f3d8da.png)

Output is square:

![image](https://user-images.githubusercontent.com/276504/89265499-e19c9400-d634-11ea-962c-37dcf654aca2.png)

**Comment by micsche** [comment]
Can you try opening map.png. Drawing circle where you require it.
Then use the -m to process map.png directly.

In the meantime I'll see if Kicad saves board edges information.

Mike

**Comment by micsche** [comment]
Hi Tomas,

Can you send me a sample of a circular PCB board?
Or else some step by step how to create such a board.

Thanks Mike

**Comment by Harvie** [comment]
Very simple. Just add non-intersecting closed shapes to the edge cuts layer:

![image](https://user-images.githubusercontent.com/276504/89507102-58b86080-d7cc-11ea-9f86-37c8e04da26b.png)

Then use 3D viewer in kicad/pcbnew menu to verify that your board is correctly cut.

**Comment by micsche** [comment]
Uploaded the updates for edgecuts. Will only do polygons and circles for
now!! Will do arcs later on.
Mike

**Comment by Harvie** [comment]
Now this is epic!
![image](https://user-images.githubusercontent.com/276504/89867828-0ef7bd80-dbb2-11ea-9685-4a6b6050f72d.png)

(i had to export the shape to DXF and then subdivide all the arcs to 0.3mm segments using https://github.com/vlachoudis/bCNC/ and import it back to kicad)

**Comment by micsche** [comment]
Does the cutout - cut some nets ? like shown?
[image: image.png]

**Comment by Harvie** [comment]
> Does the cutout - cut some nets ? like shown?

What do you mean?

**Comment by micsche** [comment]
It is remotely possible that the edge cuts could possibly disconnect whole
NETs into two (for example the red net shown).

I have two methods to perform the cutouts: before or after calculating the
dilated track.
I chose the latter. I test the program using some of my pcbs.  Both have
mathematical guarantees of not affecting track connections.
But the former method is *safer*.

So in the end double check the output before committing.

Mike

**Comment by Harvie** [comment]
I guess the worst case scenario is that you will have to connect two pads using blob of solder. This will be mostly used for prototyping anyway...

**Comment by micsche** [comment]
Want to make the best algorithm around Kicad features. :)

**Comment by micsche** [comment]
Added edge arcs also !!

Need to test all possible permutations.

**Comment by micsche** [comment]
Why did you have to "i had to export the shape to DXF and then subdivide all the arcs to 0.3mm segments" ??

**Comment by Harvie** [comment]
> Why did you have to "i had to export the shape to DXF and then subdivide all the arcs to 0.3mm segments" ??

I did it before, because there was bug in older version of kicad when working with arcs. Also autorouter seems to work faster that way. So it was good match for when you said:

> Will only do polygons and circles for now!! Will do arcs later on.
