### ISSUE TITLE
Non-circular holes

### ISSUE THREAD

**Issue by Harvie** [micsche/kicad-laser-min#3]
Can you please add support for oval holes? Eg.:

![image](https://user-images.githubusercontent.com/276504/89265069-3c81bb80-d634-11ea-90bc-80d75bdc2b7e.png)

**Comment by Harvie** [comment]
These can be easily added as well:

![image](https://user-images.githubusercontent.com/276504/89870373-0b663580-dbb6-11ea-953c-bd17ee5b6c20.png)

**Comment by micsche** [comment]
The graphic footprint?

**Comment by micsche** [comment]
Have a problem with Oval Holes - the gcode to make them is quite complex. 
Maybe can approximate them with rectangle holes!!

**Comment by Harvie** [comment]
Complex? It's two G2 arcs and two G1 lines...

Pretty much like this:

![image](https://user-images.githubusercontent.com/276504/89886326-bc77ca80-dbcc-11ea-945b-dcf86f558114.png)

All you need to know are the blue dots. (start and end of G2 arc), then you need the black dot (center of the G2 arc) which is exactly in the middle between the two blue dots. easy peasy.

**Comment by micsche** [comment]
thats not oval thats rounded rectangle :)
Kicad stores these in rr format - need to think about it how to convert into gcode.

**Comment by Harvie** [comment]
Rounded rectangle would look like this:
![image](https://user-images.githubusercontent.com/276504/89886483-fba61b80-dbcc-11ea-94a4-808e6f758436.png)

However i am pretty sure kicad only uses the exact shape i described before. 

I've also noticed you got it wrong in map.png:

![image](https://user-images.githubusercontent.com/276504/89886618-327c3180-dbcd-11ea-8d2c-796ce48f37a4.png)

For something that actualy should look like this:

![image](https://user-images.githubusercontent.com/276504/89886753-7111ec00-dbcd-11ea-8942-81acaba43337.png)

**Comment by micsche** [comment]
can you give me the pcb file?

**Comment by Harvie** [comment]
Unfortunately i am not copyright holder of this file, but it can be easily recreated as described in https://github.com/micsche/kicad-laser-min/issues/3#issuecomment-671782186
(you might also want to rotate the component by some uneven degree, eg.: 32° to test the edge cases)

I've just double checked and kicad only knows two shapes of THT holes. circular one. And the one that looks like athletic oval described in https://github.com/micsche/kicad-laser-min/issues/3#issuecomment-671859766
if you double click at the pad you will see there are no other options...

**Comment by Harvie** [comment]
After doubleclicking the pad in pcbnew:

![image](https://user-images.githubusercontent.com/276504/89887387-73287a80-dbce-11ea-9547-c8fb44063e7d.png)

**Comment by micsche** [comment]
Corrected rotation in pads. Pls test. Still using ellipses however not stadium shape :)

As for holes will tackle later on.

**Comment by Harvie** [comment]
Orientation now seems to be fixed:

![image](https://user-images.githubusercontent.com/276504/89897919-17ff8380-dbe0-11ea-8526-18f9e83eaf1c.png)

**Comment by Harvie** [comment]
BTW i wonder why you don't use GERBV (or similar tool) to convert gerbers to PNG http://gerbv.geda-project.org/
That way you would not have to parse individual features from kicad file. Also any EDA software can export to gerbers, so you would be able to support all of them instead of just kicad.

**Comment by micsche** [comment]
Stadium shaped holes complete. Please test.

**Comment by Harvie** [comment]
Looks good:

![image](https://user-images.githubusercontent.com/276504/90022056-536a8280-dcb2-11ea-9364-16643ef5ae24.png)
