### ISSUE TITLE
Possible optimization

### ISSUE THREAD

**Issue by Harvie** [micsche/kicad-laser-min#4]
I just had an idea... What takes the most time to process? The voronoi algorithm or the edge detection?

If the voronoi is significantly slower than the edge detection, you can simply process the voronoi in low resolution (same as you do now) and then upscale the resulting voronoi bitmap to be 2 or 3 times the size before detecting the edges (eg. replace each pixel with 2x2 pixels of the same color). In this setup the voronoi will be fast, but the edge detection will be more precise (=leaving smaller gaps between lines).

But if the edge detection is the slower part it will obviously not work.

**Comment by micsche** [comment]
Edge detection is fast.

It is the Voronoi that takes time.
With downscaling one has to be sure that tracks that are too close, do not
get connected.
Possibly one could downscale - perform Voronoi until before regions meet,
upscale again then finish off with high resolution processin.

Mike

**Comment by Harvie** [comment]
That is not exactly what i've meant. I don't mean to downscale before voronoi. I mean to upscale before edge detection.
(Target is to get more precise edge detection without need to increase voronoi resolution/time)

**Comment by Harvie** [comment]
In order to reduce these edge-detection gaps and artifacts without need for increasing voronoi resolution:

![image](https://user-images.githubusercontent.com/276504/90034279-b236f880-dcc0-11ea-9c6d-c0af356994ac.png)

**Comment by Harvie** [comment]
Maybe it might even help to slightly blur the upscaled image before doing the edge detection...

**Comment by micsche** [comment]
Used another thinning algorithm. output is much better

**Comment by Harvie** [comment]
> Used another thinning algorithm. output is much better

Do you have any screenshots comparing the output before/after?

**Comment by micsche** [comment]
![double_seperation](https://user-images.githubusercontent.com/31069932/104807133-d309f980-57dc-11eb-8a3e-dbba99230b3a.png)

New thinning and increased distance between two paths. The lines next to the drill holes is a new feature to differentiate pads holes from via holes.

**Comment by Harvie** [comment]
Looks much cleaner now. Can this be configured? I am afraid that cutting single line twice can be problem when doing very small traces (SMD footprints?) on milling machines with backlash. Even cutting the exact same line twice can result in two slightly different lines due to backlash. Also the distance between the two lines should be as small as possible. But generaly speaking i beleive this new approach will greatly improve reliability of isolation.

**Comment by micsche** [comment]
The double segregation lines can be closer by increasing the pixel per mm vector to raster conversion. In fact I do mine now at 60pxmm instead of default 30pxmm. But it is 4 times slower per side. Tried parallel processing, little luck, and would complicate processing at the image division edges immensely.

Tried to reduce seperation programmatically, however i am down a difference to one image process (erosion) to none at all. So no leverage there. Also tried different erosion kernel from a cross of 1s instead of square of 1s, but result was awful. 

SMD, I agree,  would be issue. Will make double segregation as an option setting.
