### ISSUE TITLE
Euclidean voronoi

### ISSUE THREAD

**Issue by Harvie** [micsche/kicad-laser-min#5]
Found this image at https://en.wikipedia.org/wiki/Voronoi_diagram#Illustration

![image](https://user-images.githubusercontent.com/276504/90035025-9ed85d00-dcc1-11ea-96db-eff402b6a771.png)

Seems to me that currently the manhattan is used. Maybe the euclidean would produce cleaner looking boards. But i am not sure how hard would it be to implement pixel-wise.

**Comment by micsche** [comment]
PCB isolation uses Line Voronoi not pixel Voronoi. Tried to find algorithms
ready for this type but to no avail.
What I can do to speed things up is to replace the OpenCV API to image
retrieval and perform a pure image data array algorithm.
That should make memory requests faster.
